branches:
  only: ["master"]

before_install:
  - . /etc/os-release
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install buildah

script: ./build.sh

after_success:
  - buildah push localhost/gongt/nginx oci-archive:./.cache/nginx.oci:gongt/nginx:latest

before_script:
  - buildah pull oci-archive:./.cache/nginx.oci

cache:
  directories:
    - .cache
