#!/bin/bash

doClone() {
	git submodule add "$url" "$path"
}

path=source/nginx
url=git@github.com:nginx/nginx.git
doClone

path=source/modules/echo-nginx-module
url=git@github.com:openresty/echo-nginx-module.git
doClone

path=source/modules/headers-more-nginx-module
url=git@github.com:openresty/headers-more-nginx-module.git
doClone

path=source/modules/ngx_cache_purge
url=git@github.com:FRiCKLE/ngx_cache_purge.git
doClone

path=source/modules/memc-nginx-module
url=git@github.com:openresty/memc-nginx-module.git
doClone

path=source/modules/ngx_devel_kit
url=git@github.com:simplresty/ngx_devel_kit.git
doClone

path=source/modules/nginx_cookie_flag_module
url=git@github.com:AirisX/nginx_cookie_flag_module.git
doClone

path=source/modules/ngx_brotli
url=git@github.com:google/ngx_brotli.git
doClone

path=source/modules/nginx_accept_language_module
url=git@github.com:giom/nginx_accept_language_module.git
doClone

path=source/modules/ngx-fancyindex
url=git@github.com:aperezdc/ngx-fancyindex.git
doClone

path=source/modules/traffic-accounting-nginx-module
url=git@github.com:Lax/traffic-accounting-nginx-module.git
doClone

path=source/modules/ngx_log_if
url=git@github.com:cfsego/ngx_log_if.git
doClone

path=source/modules/nchan
url=git@github.com:slact/nchan.git
doClone

path=source/modules/ngx_http_geoip2_module
url=git@github.com:leev/ngx_http_geoip2_module.git
doClone

path=source/special-modules/njs
url=git@github.com:nginx/njs.git
doClone

path=source/modules/lua-nginx-module
url=git@github.com:openresty/lua-nginx-module.git
doClone

path=source/luajit2
url=git@github.com:openresty/luajit2.git
doClone

path=source/resty/lua-resty-lrucache
url=git@github.com:openresty/lua-resty-lrucache.git
doClone

path=source/resty/lua-resty-core
url=git@github.com:openresty/lua-resty-core.git
doClone

path=source/lua/luaposix
url=git@github.com:luaposix/luaposix.git
doClone

path=common
url=git@github.com:GongT/contaners-builder.git
doClone
